=== mathieuguyot/perCEPtion/resources/test/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


	<!-- Création de type personnalisé -->
	
	<!-- Durée d'un jeu de données -->
	<xsd:simpleType name="heure_type">
    	<xsd:restriction base="xsd:integer">
        	<xsd:minInclusive value="0" />
    	</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="minute_type">
    	<xsd:restriction base="xsd:integer">
        	<xsd:minInclusive value="0" />
        	<xsd:maxInclusive value="60" />
    	</xsd:restriction>
	</xsd:simpleType>
		
	<!-- Type destiné à la production des pannaeau et
		 la consommaion de la maison -->
	<xsd:simpleType name="energie">
    	<xsd:restriction base="xsd:double">
        	<xsd:minInclusive value="0"/>
    	</xsd:restriction>
	</xsd:simpleType>
	
	<!-- Un jeu de données s'applique soit sur une période creuse soit sur
		 période pleine -->
	<xsd:simpleType name="periode_type">
    	<xsd:restriction base="xsd:string">
        	<xsd:enumeration value="pleine" />
            <xsd:enumeration value="creuse" />
    	</xsd:restriction>
	</xsd:simpleType>
	
	
	
	<!-- Schéma XML -->

	<xsd:element name="duree">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="heures" type="heure_type" minOccurs="1"/>
				<xsd:element name="minutes" type="minute_type" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="jeudedonnees">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="duree"/>
				<xsd:element name="consomation" type="energie"/>
				<xsd:element name="production" type="energie"/>
			</xsd:sequence>
			<xsd:attribute name="periode" use="required" type="periode_type"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="scenario">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="jeudedonnees"  minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="data">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="scenario"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== mathieuguyot/perCEPtion/resources/test/valideXMLFIle.xml
<?xml version="1.0" encoding="UTF-8"?>
<data
        xs:noNamespaceSchemaLocation="schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <scenario>
        <jeudedonnees periode="pleine">
            <duree>
                <heures>12</heures>
                <minutes>45</minutes>
            </duree>
            <consomation>76.65</consomation>
            <production>89.12</production>
        </jeudedonnees>
        <jeudedonnees periode="creuse">
            <duree>
                <heures>10</heures>
                <minutes>60</minutes>
            </duree>
            <consomation>678</consomation>
            <production>431.90</production>
        </jeudedonnees>
    </scenario>
</data>
