=== mathieuguyot/perCEPtion/perCEPtion/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">


	<!-- Création de type personnalisé -->
	
	<!-- Type d'event -->
	<!--<xsd:simpleType name="primitive_event_type_type">
    	<xsd:restriction base="xsd:string">
			<xsd:enumeration value="PEG_Blank"/>
			<xsd:enumeration value="PEG_Co_ResponseTime"/>
			<xsd:enumeration value="PEG_Pm_Cpu"/>
			<xsd:enumeration value="PEG_Pm_Disk"/>
			<xsd:enumeration value="PEG_Pm_Ram"/>
			<xsd:enumeration value="PEG_Vm_Cpu"/>
			<xsd:enumeration value="PEG_Vm_Disk"/>
			<xsd:enumeration value="PEG_Vm_Ram"/>
    	</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="simple_event_type_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="SEG_Cpu_Drop"/>
            <xsd:enumeration value="SEG_Cpu_Overload"/>
			<xsd:enumeration value="SEG_Ram_Drop"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="complex_event_type_type">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="CEG_Cpu_Dead"/>
		</xsd:restriction>
	</xsd:simpleType>-->

	<xsd:simpleType name="primitive_event_type_type">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="simple_event_type_type">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="complex_event_type_type">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<!-- Temps d'intervalle entre deux exécutions -->
	<xsd:simpleType name="event_name_runtime">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0"/>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="event_name_type">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>

	<xsd:simpleType name="event_activated">
		<xsd:restriction base="xsd:boolean"/>
	</xsd:simpleType>
	
	
	<!-- Schéma XML -->

		<!-- Primitive events -->
	<xsd:element name="primitive">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="event_name_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="type" type="primitive_event_type_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="runtime" type="event_name_runtime" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
            <xsd:attribute name="enabled" use="required" type="event_activated"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="primitives">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="primitive" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

		<!-- Simple and complex events -->
	<xsd:element name="param">
		<xsd:complexType>
			<xsd:simpleContent>
				<xsd:extension base="xsd:string">
					<xsd:attribute name="tag" use="required" type="xsd:string"/>
					<xsd:attribute name="type" use="required" type="xsd:string"/>
				</xsd:extension>
			</xsd:simpleContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="params">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="param" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

		<!-- Simple events -->
	<xsd:element name="simple">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="event_name_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="type" type="simple_event_type_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="params" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="enabled" use="required" type="event_activated"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="simples">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="simple" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

		<!-- Complex events -->
	<xsd:element name="complexe">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="event_name_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element name="type" type="complex_event_type_type" minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="params" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
			<xsd:attribute name="enabled" use="required" type="event_activated"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="complexes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="complexe" minOccurs="1" maxOccurs="unbounded"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<!-- Events -->
	<xsd:element name="events">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="primitives"  minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="simples"  minOccurs="1" maxOccurs="1"/>
				<xsd:element ref="complexes"  minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="perception">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="events" minOccurs="1" maxOccurs="1"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParser/PrimitiveEvents/testParse_XMLFileParser_OK.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>PEG_Pm_Cpu1</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>12000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>PEG_Pm_Disk1</name>
                <type>PEG_Pm_Disk</type>
                <runtime>89100</runtime>
            </primitive>
        </primitives>
        <simples>
            <simple enabled="false">
                <name>SEG_Cpu_Drop1</name>
                <type>SEG_Cpu_Drop</type>
                <params>
                    <param tag="runtime" type="Integer">12</param>
                </params>
            </simple>
        </simples>
        <complexes>
            <complex enabled="false">
                <name>CEG_Dead_Cpu1</name>
                <type>CEG_Dead_Cpu</type>
                <params>
                    <param tag="runtime" type="Integer">12</param>
                </params>
            </complex>
        </complexes>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>MonPEGPmCpu</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>1000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>MonPEGPmDisk</name>
                <type>PEG_Pm_Disk</type>
                <runtime>1000</runtime>
            </primitive>
            <primitive enabled="true">
                <name>MonPEGPmDiskActivated</name>
                <type>PEG_Pm_Disk</type>
                <runtime>2000</runtime>
            </primitive>
        </primitives>
        <simples>
            <simple enabled="true">
                <name>MonSimpleEvent1</name>
                <type>SEG_Cpu_Drop</type>
                <params>
                    <param tag="tag1" type="Long">45958</param>
                    <param tag="tag2" type="String">Param1</param>
                    <param tag="tag3" type="String">param2</param>
                    <param tag="tag4" type="Integer">78</param>
                </params>
            </simple>
        </simples>
        <complexes>
            <complexe enabled="true">
                <name>MonSimpleEvent1</name>
                <type>CEG_Cpu_Dead</type>
                <params>
                    <param tag="tag1" type="Long">45958</param>
                    <param tag="tag2" type="String">Param1</param>
                    <param tag="tag3" type="String">param2</param>
                    <param tag="tag4" type="Integer">78</param>
                </params>
            </complexe>
            <complexe enabled="true">
                <name>MonSimpleEvent2</name>
                <type>CEG_Cpu_Dead</type>
                <params>
                    <param tag="ip4" type="Long">1245</param>
                    <param tag="port" type="String">localhost:8080</param>
                    <param tag="monParam3" type="String">param3</param>
                    <param tag="monParam4" type="Integer">45</param>
                </params>
            </complexe>
        </complexes>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParserTest/PrimitiveEvents/testParse_XMLFileParser_OK.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>PEG_Blank1</name>
                <type>PEG_Blank</type>
                <runtime>78945</runtime>
            </primitive>
            <primitive enabled="true">
                <name>PEG_Pm_Cpu1</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>12000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>PEG_Pm_Disk1</name>
                <type>PEG_Pm_Disk</type>
                <runtime>89100</runtime>
            </primitive>
        </primitives>
    </events>
</perception>

=== mathieuguyot/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParserTest/testDoNotParseIfInvalidPatternFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>MonPEGBlank</name>
                <type>PEG_Blank</type>
                <runtime>coucouJeSuisUneBelleErreur</runtime>
            </primitive>
            <primitive enabled="true">
                <name>MonPEGPmCpu</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>12000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>MonPEGPmDisk</name>
                <type>PEG_Pm_Disk</type>
                <runtime>89100</runtime>
            </primitive>
        </primitives>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParserTest/SimpleEvents/testParse_valideFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <simples>
            <simple enabled="true">
                <name>MonSimpleEvent1</name>
                <type>SimpleEvent1</type>
                <params>
                    <param tag="tag1" type="Long">45958</param>
                    <param tag="tag2" type="String">Param1</param>
                    <param tag="tag3" type="String">param2</param>
                    <param tag="tag4" type="Integer">78</param>
                </params>
            </simple>
            <simple enabled="true">
                <name>MonSimpleEvent2</name>
                <type>SimpleEvent2</type>
                <params>
                    <param tag="ip4" type="Long">1245</param>
                    <param tag="port" type="String">localhost:8080</param>
                    <param tag="monParam3" type="String">param3</param>
                    <param tag="monParam4" type="Integer">45</param>
                </params>
            </simple>
        </simples>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParser/PrimitiveEvents/testIsEnabledPrimitiveEvent_OK_EnabledFalse.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="false">
                <name>e1</name>
                <type>PEG_Vm_Disk</type>
                <runtime>700</runtime>
            </primitive>
            <primitive enabled="true">
                <name>e2</name>
                <type>PEG_Vm_Cpu</type>
                <runtime>1100</runtime>
            </primitive>
        </primitives>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileParserTest/PrimitiveEvents/testGetPrimitiveEventRuntimeFromFile_KO.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>hey</name>
                <type>PEG_Co_ResponseTime</type>
            </primitive>
            <primitive enabled="true">
                <name>event2</name>
                <type>PEG_Vm_Cpu</type>
                <runtime>11000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>event3</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>98000</runtime>
            </primitive>
        </primitives>
    </events>
</perception>

=== mathieuguyot/perCEPtion/perCEPtion/src/test/resources/testingXMLFiles/XMLFileValidatorTest/SimpleEvents/testValidate_InvalidSimpleEventTypeConflictingParamType.xml
<?xml version="1.0" encoding="UTF-8"?>
<perception
        xs:noNamespaceSchemaLocation="../../../../../../resources/schema.xsd"
        xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
>
    <events>
        <primitives>
            <primitive enabled="true">
                <name>MonPEGBlank</name>
                <type>PEG_Blank</type>
                <runtime>12000</runtime>
            </primitive>
            <primitive enabled="true">
                <name>MonPEGPmCpu</name>
                <type>PEG_Pm_Cpu</type>
                <runtime>12000</runtime>
            </primitive>
            <primitive enabled="false">
                <name>MonPEGPmDisk</name>
                <type>PEG_Pm_Disk</type>
                <runtime>89100</runtime>
            </primitive>
        </primitives>
        <simples>
            <simple enabled="true">
                <name>MonSimpleEvent1</name>
                <type>SE_Cpu_Drop</type>
                <params>
                    <param tag="tag1" type="Integer">blabla</param>
                    <param tag="tag2" type="String">Param1</param>
                    <param tag="tag3" type="String">param2</param>
                    <param tag="tag4" type="Integer">78</param>
                </params>
            </simple>
            <simple enabled="true">
                <name>MonSimpleEvent2</name>
                <type>SEG_Cpu_Overload</type>
                <params>
                    <param tag="ip4" type="Long">1245</param>
                    <param tag="port" type="String">localhost:8080</param>
                    <param tag="monParam3" type="String">param3</param>
                    <param tag="monParam4" type="Integer">45</param>
                </params>
            </simple>
        </simples>
        <complexes>
            <complex enabled="true">
                <name>MonSimpleEvent1</name>
                <type>CE_Cpu_Dead</type>
                <params>
                    <param tag="tag1" type="Long">45958</param>
                    <param tag="tag2" type="String">Param1</param>
                    <param tag="tag3" type="String">param2</param>
                    <param tag="tag4" type="Integer">78</param>
                </params>
            </complex>
            <complex enabled="true">
                <name>MonSimpleEvent2</name>
                <type>CE_Cpu_Dead</type>
                <params>
                    <param tag="ip4" type="Long">1245</param>
                    <param tag="port" type="String">localhost:8080</param>
                    <param tag="monParam3" type="String">param3</param>
                    <param tag="monParam4" type="Integer">45</param>
                </params>
            </complex>
        </complexes>
    </events>
</perception>
